Repository PersistentSS13/Nebula, pull requests merged in 2022-05, with the labels that each got.

#266 Feb Kleibkhar fixes
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/mining.dm
  mods/persistence/game/turfs/exterior/_exterior.dm
  mods/persistence/modules/overmap/ships/landable.dm
Labels: question

#278 Alter Character Creation Process
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/initialization/chargen.dm
  mods/persistence/modules/client/preference_setup/general/01_basic.dm
  mods/persistence/modules/client/preference_setup/general/05_flavor.dm
  mods/persistence/modules/client/preference_setup/preference_setup.dm
  mods/persistence/modules/client/preferences.dm
  mods/persistence/modules/mob/new_player.dm
Labels: waiting on author

#295 Add Character Selection/Deletion, Protect against Duplicates
  mods/persistence/controllers/subsystems/initialization/chargen.dm
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/game/machinery/cryopod.dm
  mods/persistence/modules/client/preferences.dm
  mods/persistence/modules/mob/new_player.dm
  mods/persistence/modules/world_save/serializers/one_off_serializer.dm
  sql/V100__Persistence.sql
Labels: enhancement

#294 Map changes
  code/modules/fabrication/designs/imprinter/designs_misc_circuits.dm
  maps/kleibkhar/kleibkhar-1.dmm
  maps/kleibkhar/kleibkhar-2.dmm
  maps/kleibkhar/kleibkhar-3.dmm
  maps/kleibkhar/kleibkhar-4.dmm
  maps/kleibkhar/kleibkhar-overmap.dmm
  maps/kleibkhar/kleibkhar.dm
  maps/kleibkhar/kleibkhar_areas.dm
  maps/kleibkhar/kleibkhar_defines.dm
  maps/kleibkhar/kleibkhar_exoplanet.dm
  maps/kleibkhar/kleibkhar_overmap.dm
  maps/kleibkhar/kleibkhar_supply.dm
  maps/kleibkhar/kleibkhar_turf.dm
  maps/kleibkhar/kleibkhar_unit_testing.dm
  maps/kleibkhar/kleibkhar_zlevels.dm
  maps/utility/cargo_shuttle_tmpl.dm
  maps/utility/cargo_shuttle_tmpl.dmm
  mods/persistence/_persistence.dme
  mods/persistence/game/machinery/resleever.dm
  mods/persistence/modules/atmospherics/components/injector.dm
  mods/persistence/modules/atmospherics/components/vents.dm
  mods/persistence/modules/fabrication/designs/imprinter/designs_misc_circuits.dm
  mods/persistence/modules/power/lighting.dm
Labels: enhancement

#301 Fixed a few annoyances with the kleibkhar map
  maps/kleibkhar/kleibkhar-3.dmm
Labels: enhancement

#308 Imported old animated fountain icon
  icons/obj/fountain.dmi
Labels: enhancement
