Repository PersistentSS13/Nebula, pull requests merged in 2022-07, with the labels that each got.

#323 Gun and storage clothing saving
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/datums/extensions/holster.dm
  mods/persistence/game/objects/items/weapons/storage.dm
  mods/persistence/modules/clothing/_clothing.dm
  mods/persistence/modules/clothing/under/accessories/storage.dm
  mods/persistence/modules/projectiles/ammunition.dm
  mods/persistence/modules/projectiles/guns/projectile.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
  mods/persistence/modules/world_save/serializers/one_off_serializer.dm
Labels: bug, waiting on author

#333 Make solar panels not save their control computer
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: bug

#332 Gives DIY Stirling kit generator its vital components
  mods/persistence/modules/chargen/storage/industrial_boxes.dm
Labels: bug

#335 Open testing fixes
  mods/persistence/_persistence.dme
  mods/persistence/icons/obj/action_buttons/actions.dmi
  mods/persistence/modules/client/preferences.dm
  mods/persistence/modules/mob/death.dm
  mods/persistence/modules/mob/mob.dm
  mods/persistence/modules/mob/new_player.dm
  mods/persistence/modules/mob/observer/limbo.dm
  mods/persistence/modules/organs/internal/stack.dm
  mods/persistence/modules/world_save/serializers/one_off_serializer.dm
  mods/persistence/modules/world_save/wrappers/weakref_wrapper.dm
Labels: bug

#267 Removes unsafe Shuttle and AI verbs from admin panels
  mods/persistence/_persistence.dm
Labels: :arrow_down_small: Pull Request

#336 Now also check for the stack during language update.
  mods/persistence/modules/organs/internal/stack.dm
Labels: bug

#316 Adds a variety of early-game and early-mid-game firearms
  mods/persistence/game/objects/items/weapons/guns/tier0/boltaction.dm
  mods/persistence/game/objects/items/weapons/guns/tier0/lasrifle.dm
  mods/persistence/game/objects/items/weapons/guns/tier0/revolver.dm
  mods/persistence/game/objects/items/weapons/guns/tier0/shotgun.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/boltaction.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/laspistol.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/lasrifle.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/pistol.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/pistol_gold.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/revolver.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/shotgun_db.dm
  mods/persistence/game/objects/items/weapons/guns/tier1/shotgun_pump.dm
  mods/persistence/icons/obj/guns/tier0/boltaction.dmi
  mods/persistence/icons/obj/guns/tier0/lasrifle.dmi
  mods/persistence/icons/obj/guns/tier0/revolver.dmi
  mods/persistence/icons/obj/guns/tier0/shotgun.dmi
  mods/persistence/icons/obj/guns/tier1/boltaction.dmi
  mods/persistence/icons/obj/guns/tier1/laspistol.dmi
  mods/persistence/icons/obj/guns/tier1/lasrifle.dmi
  mods/persistence/icons/obj/guns/tier1/pistol.dmi
  mods/persistence/icons/obj/guns/tier1/pistol_gold.dmi
  mods/persistence/icons/obj/guns/tier1/revolver.dmi
  mods/persistence/icons/obj/guns/tier1/shotgun_db.dmi
  mods/persistence/icons/obj/guns/tier1/shotgun_pump.dmi
Labels: enhancement

#340 Added medical backgrounds and rebalances surgery
  mods/persistence/_persistence.dme
  mods/persistence/modules/chargen/defines/origins.dm
  mods/persistence/modules/chargen/defines/roles.dm
  mods/persistence/modules/surgery/__surgery_setup.dm
  mods/persistence/modules/surgery/_surgery.dm
Labels: enhancement

#341 Miscellaneous load fixes [MDB IGNORE] [IDB IGNORE]
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/game/machinery/cryopod.dm
  mods/persistence/game/machinery/machinery.dm
  mods/persistence/modules/chargen/launch_pod.dm
  mods/persistence/modules/clothing/suits/storage.dm
  mods/persistence/modules/mining/machinery/_material_processing.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
  mods/persistence/modules/world_save/serializers/sql_serializer.dm
  mods/persistence/modules/world_save/wrappers/area_wrapper.dm
Labels: bug, enhancement

#343 Fix chemsuit
  mods/persistence/_persistence.dme
  mods/persistence/icons/clothing/suit/chem_suit.dmi
  mods/persistence/modules/clothing/suits/utility.dm
Labels: bug

#359 Additional debug info on limbo fails
  mods/persistence/game/machinery/cryopod.dm
  mods/persistence/modules/world_save/serializers/one_off_serializer.dm
Labels: enhancement

#358 Make memories save
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: bug, enhancement

#357 Smes reload properly
  mods/persistence/game/machinery/_machines_base/stock_parts/_stock_parts.dm
  mods/persistence/game/machinery/machinery.dm
  mods/persistence/modules/power/smes.dm
Labels: enhancement

#350 More saved vars and stuff
  mods/persistence/_persistence.dme
  mods/persistence/game/objects/items/weapons/storage.dm
  mods/persistence/modules/economy/economy.dm
  mods/persistence/modules/reagents/chems/chems.dm
  mods/persistence/modules/reagents/heat_sources/heat_source.dm
  mods/persistence/modules/reagents/reagent_containers/food/food.dm
  mods/persistence/modules/reagents/reagent_containers/glass/bottle.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
  mods/persistence/modules/world_save/saved_vars/saved_overrides.dm
Labels: enhancement

#342 Prevent people from spawning with the cyberbrain
  mods/persistence/_persistence.dme
  mods/persistence/game/species/species.dm
Labels: bug

#354 Add remove limbo entry verb
  mods/persistence/__defines/logging.dm
  mods/persistence/_persistence.dm
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/mapping.dm
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/modules/admin/verbs/admin.dm
Labels: bug, enhancement

#360 Fix saving decals
  mods/persistence/game/turfs/turf.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: enhancement

#362 Prevent food reagents from resetting their reagents on load
  mods/persistence/modules/reagents/reagent_containers/food/food.dm
Labels: enhancement

#352 Prevent re-entering mob on enter lock
  mods/persistence/modules/admin/verbs/admin.dm
  mods/persistence/modules/client/preferences.dm
  mods/persistence/modules/mob/new_player.dm
Labels: enhancement

#361 Improved chargen pods
  code/game/turfs/unsimulated/floor.dm
  maps/chargen/chargen.dmm
  maps/chargen/chargen_objects.dm
  mods/persistence/modules/chargen/dossier_console.dm
  mods/persistence/modules/chargen/launch_pod.dm
Labels: enhancement

#365 Grown food bugfix
  code/modules/hydroponics/grown.dm
Labels: bug, Send Upstream

#363 Add iv drip recipe
  mods/persistence/_persistence.dme
  mods/persistence/modules/materials/definitions/materials_solid_metal.dm
  mods/persistence/modules/materials/recipes_persistence.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: enhancement

#364 Fix invisible underwear
  mods/persistence/modules/clothing/_clothing.dm
Labels: bug

#368 Fix for mask making people bald, and bad top hat sprite
  code/game/gamemodes/wizard/servant_items/caretaker.dm
  code/game/gamemodes/wizard/servant_items/fiend.dm
  code/game/gamemodes/wizard/servant_items/overseer.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/earmuffs.dm
  code/modules/clothing/head/fated_key.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/headphones.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/clothing/head/tophat.dmi
  mods/content/corporate/clothing/head/captain.dm
Labels: bug

#367 Allows HE pipes to interact with exterior turfs
  code/modules/atmospherics/datum_pipeline.dm
  code/modules/atmospherics/he_pipes.dm
Labels: Send Upstream
