Repository PersistentSS13/Nebula, pull requests merged in 2022-08, with the labels that each got.

#371 Fix verb to auto kick players and lock server
  mods/persistence/modules/admin/verbs/admin.dm
Labels: bug

#373 Terraforming
  maps/kleibkhar/kleibkhar_turf.dm
  mods/persistence/modules/hydroponics/trays.dm
Labels: enhancement

#374 Fixes material smelting temperatures
  code/modules/materials/definitions/solids/materials_solid_mineral.dm
Labels: bug, Send Upstream

#370 July 30 Persistence fixes
  maps/kleibkhar/kleibkhar_turf.dm
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/autosave.dm
  mods/persistence/controllers/subsystems/mining.dm
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/game/area/area_space.dm
  mods/persistence/modules/admin/verbs/admin.dm
  mods/persistence/modules/detectivework/evidence/_evidence_type.dm
  mods/persistence/modules/modular_computers/networking/device_types/_network_device.dm
  mods/persistence/modules/overmap/overmap_shuttle.dm
  mods/persistence/modules/shuttles/landmarks.dm
  mods/persistence/modules/world_save/serializers/sql_serializer.dm
Labels: bug

#376 Improve Dockerfile order efficency
  Dockerfile
Labels: operations

#372 Add rng trees and plant distribution
  maps/kleibkhar/kleibkhar_turf.dm
  mods/persistence/modules/hydroponics/trays.dm
Labels: enhancement

#375 RND adjustments
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/initialization/fabrication.dm
  mods/persistence/modules/science/files/design.dm
  mods/persistence/modules/science/files/writer.dm
  mods/persistence/modules/science/recipe.dm
  mods/persistence/modules/science/research_overrides.dm
Labels: enhancement

#377 Add image build publish on release
  .github/workflows/publish_image_on_release.yml
Labels: operations

#378 Add sql image publishing
  .github/workflows/publish_image_on_release.yml
Labels: operations

#379 Migrate to ghcr
  Dockerfile
Labels: operations
