Repository PersistentSS13/Nebula, pull requests merged in 2023-03, with the labels that each got.

#405 Adds network finance system
  code/__defines/computers.dm
  code/__defines/machinery.dm
  code/__defines/subsystem-priority.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/accounts.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/ticker.dm
  code/datums/outfits/jobs/job.dm
  code/game/jobs/job/_job.dm
  code/game/machinery/_machines_base/stock_parts/money_printer.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/game/objects/items/weapons/circuitboards/machinery/network.dm
  code/modules/economy/cael/ATM.dm
  code/modules/economy/cael/Accounts.dm
  code/modules/economy/cael/Accounts_DB.dm
  code/modules/economy/cael/EFTPOS.dm
  code/modules/economy/cael/Transactions.dm
  code/modules/economy/cael/account_mod.dm
  code/modules/economy/cael/escrow.dm
  code/modules/economy/cael/global_accounts.dm
  code/modules/economy/cael/related_accounts.dm
  code/modules/events/money_hacker.dm
  code/modules/events/money_lotto.dm
  code/modules/fabrication/designs/general/designs_general.dm
  code/modules/fabrication/designs/protolathe/designs_computer_accessories.dm
  code/modules/goals/definitions/personal.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/modular_computers/file_system/programs/command/finances.dm
  code/modules/modular_computers/file_system/programs/generic/atm.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  code/modules/modular_computers/file_system/programs/generic/folding.dm
  code/modules/modular_computers/file_system/programs/generic/ntdownloader.dm
  code/modules/modular_computers/networking/_network.dm
  code/modules/modular_computers/networking/accounts/_network_accounts.dm
  code/modules/modular_computers/networking/accounts/account.dm
  code/modules/modular_computers/networking/accounts/id_card.dm
  code/modules/modular_computers/networking/device_types/bank.dm
  code/modules/modular_computers/networking/emails/_email.dm
  code/modules/modular_computers/networking/finance/money_accounts.dm
  code/modules/modular_computers/networking/finance/money_cube.dm
  code/modules/modular_computers/networking/finance/network_finance.dm
  code/modules/modular_computers/networking/finance/network_pos.dm
  code/modules/modular_computers/networking/machinery/bank.dm
  code/modules/modular_computers/networking/machinery/modem.dm
  code/modules/modular_computers/os/_os.dm
  code/modules/modular_computers/os/files.dm
  config/example/game_options.txt
  icons/obj/items/money_cube.dmi
  maps/~mapsystem/maps.dm
  maps/~mapsystem/maps_currency.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
  nano/templates/accounts_terminal.tmpl
  nano/templates/atm_program.tmpl
  nano/templates/banking_mainframe.tmpl
  nano/templates/finance_management.tmpl
  nano/templates/identification_computer.tmpl
  nano/templates/network_pos.tmpl
  nebula.dme
Labels: enhancement

#407 Add stopgap fix for #406
  mods/persistence/modules/fabrication/_fabricator.dm
Labels: bug

#418 Network Finance saving
  code/controllers/subsystems/ticker.dm
  code/modules/economy/cael/related_accounts.dm
  code/modules/events/money_lotto.dm
  code/modules/modular_computers/computers/subtypes/preset_console.dm
  code/modules/modular_computers/networking/_network.dm
  code/modules/modular_computers/networking/finance/money_accounts.dm
  code/modules/modular_computers/networking/finance/money_cube.dm
  mods/persistence/_persistence.dme
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/datums/extensions/extensions.dm
  mods/persistence/modules/detectivework/evidence/_evidence_holder.dm
  mods/persistence/modules/economy/account.dm
  mods/persistence/modules/economy/economy.dm
  mods/persistence/modules/modular_computers/networking/_network.dm
  mods/persistence/modules/modular_computers/networking/accounts/account.dm
  mods/persistence/modules/modular_computers/networking/finance/bank.dm
  mods/persistence/modules/modular_computers/networking/finance/money_cube.dm
  mods/persistence/modules/world_save/_persistence.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
  mods/persistence/modules/world_save/serializers/json_serializer.dm
  mods/persistence/modules/world_save/serializers/one_off_serializer.dm
  mods/persistence/modules/world_save/serializers/sql_serializer.dm
  mods/persistence/modules/world_save/wrappers/escrow_holder.dm
  mods/persistence/modules/world_save/wrappers/extensions/_extension_wrapper.dm
  nano/templates/atm_program.tmpl
Labels: enhancement, economy

#436 Prevent doors updating connections on load
  mods/persistence/game/machinery/doors/_door.dm
Labels: serialization

#428 Add saved vars for a few things
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: serialization

#434 Fix missing internet machine stuff
  code/modules/fabrication/designs/imprinter/designs_misc_circuits.dm
  code/modules/overmap/internet/internet_circuitboards.dm
  code/modules/overmap/internet/internet_repeater.dm
  code/modules/overmap/internet/internet_uplink.dm
Labels: bug

#433 Fix offset terminal not facing the right place
  code/game/machinery/_machines_base/stock_parts/power/terminal.dm
Labels: bug

#435 Save omniport datum state
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: serialization

#430 Fix airlock sensor updating
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/embedded_controller/airlock_program.dm
Labels: bug

#429 Make posters face the right way
  code/game/objects/effects/decals/contraband.dm
Labels: bug

#427 Added disposal pipe cap
  code/modules/recycling/disposalpipe.dm
  icons/obj/pipes/disposal.dmi
Labels: enhancement

#431 Tweak some wall offsets that were wrong
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/turret_control.dm
  code/modules/modular_computers/networking/machinery/wall_relay.dm
Labels: bug

#432 Fix omni filter display
  code/modules/atmospherics/components/omni_devices/filter.dm
  nano/templates/omni_filter.tmpl
Labels: bug

#439 Cloning fixes
  mods/persistence/controllers/subsystems/initialization/chargen.dm
  mods/persistence/modules/cloning/device_types/cloning_pod.dm
  mods/persistence/modules/mob/death.dm
  mods/persistence/modules/mob/living/living.dm
  mods/persistence/modules/mob/observer/limbo.dm
  mods/persistence/modules/modular_computers/file_system/programs/cloning.dm
  mods/persistence/modules/organs/internal/stack.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
  nano/templates/cloning_program.tmpl
Labels: bug
