Repository PersistentSS13/Nebula, pull requests merged in 2023-09, with the labels that each got.

#465 Network finance fixes
  code/game/machinery/_machines_base/stock_parts/money_printer.dm
  code/modules/economy/cael/Accounts.dm
  code/modules/economy/cael/related_accounts.dm
  code/modules/modular_computers/file_system/programs/command/finances.dm
  code/modules/modular_computers/file_system/programs/generic/atm.dm
  code/modules/modular_computers/networking/_network.dm
  code/modules/modular_computers/networking/accounts/_network_accounts.dm
  code/modules/modular_computers/networking/device_types/bank.dm
  code/modules/modular_computers/networking/device_types/mainframe.dm
  code/modules/modular_computers/networking/finance/money_accounts.dm
  mods/persistence/_persistence.dme
  mods/persistence/modules/economy/account.dm
  mods/persistence/modules/modular_computers/networking/_network.dm
  mods/persistence/modules/modular_computers/networking/device_types/router.dm
  mods/persistence/modules/modular_computers/networking/finance/bank.dm
  mods/persistence/modules/modular_computers/networking/finance/money_cube.dm
  mods/persistence/modules/modular_computers/networking/machines/router.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: :beetle: bug, :heavy_dollar_sign: economy

#466 Fixes level order
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/modules/world_save/serializers/sql_serializer.dm
  mods/persistence/modules/world_save/wrappers/map_data_wrapper.dm
Labels: :beetle: bug, :floppy_disk: serialization, :milky_way: map/map gen

#467 Fixes at least one cause of missing arms on load
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/organs/internal/eyes.dm
Labels: :beetle: bug, :floppy_disk: serialization, :monkey: Mobs

#472 Fixes area controller deletion
  code/modules/mob/observer/eye/blueprints_eye.dm
  mods/persistence/modules/mob/observer/eye/area_control.dm
Labels: :floppy_disk: serialization

#473 Save logging + Fixes
  code/__defines/misc.dm
  code/__defines/time.dm
  code/_macros.dm
  code/controllers/configuration.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/machines.dm
  code/modules/client/darkmode.css
  code/modules/client/lightmode.css
  config/example/config.txt
  mods/persistence/__defines/logging.dm
  mods/persistence/__defines/serializer.dm
  mods/persistence/_persistence.dme
  mods/persistence/code/__defines/world_save.dm
  mods/persistence/code/controllers/configuration.dm
  mods/persistence/controllers/subsystems/autosave.dm
  mods/persistence/controllers/subsystems/mapping.dm
  mods/persistence/controllers/subsystems/persistence.dm
  mods/persistence/controllers/subsystems/persistence/persistence_loading.dm
  mods/persistence/controllers/subsystems/persistence/persistence_saving.dm
  mods/persistence/controllers/subsystems/persistence/persistence_stats.dm
  mods/persistence/controllers/subsystems/persistence/persistence_storage.dm
  mods/persistence/game/machinery/cryopod.dm
  mods/persistence/modules/admin/verbs/admin.dm
  mods/persistence/modules/chargen/launch_pod.dm
  mods/persistence/modules/mob/death.dm
  mods/persistence/modules/mob/new_player.dm
  mods/persistence/modules/multiz/level_data.dm
  mods/persistence/modules/overmap/sectors.dm
  mods/persistence/modules/world_save/_persistence.dm
  mods/persistence/modules/world_save/save_testing.dm
  mods/persistence/modules/world_save/saved_vars/saved_skipped.dm
  mods/persistence/modules/world_save/serializers/_serializer.dm
  mods/persistence/modules/world_save/serializers/one_off_serializer.dm
  mods/persistence/modules/world_save/serializers/sql_serializer.dm
  mods/persistence/modules/world_save/serializers/sql_serializer_db.dm
  sql/migrate/V101__Save_Logging.sql
  test/check-paths.sh
Labels: :new: enhancement, :floppy_disk: serialization
