Repository PersistentSS13/Nebula, pull requests merged in 2024-01, with the labels that each got.

#486 Outreach contamination features
  code/__defines/chemistry.dm
  code/__defines/misc.dm
  code/datums/extensions/scent/_scent.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/weapons/circuitboards/machinery/household.dm
  code/game/objects/items/weapons/soap.dm
  code/game/objects/structures/ironing_board.dm
  code/modules/ZAS/Contaminants.dm
  code/modules/clothing/_clothing.dm
  code/modules/clothing/suits/utility.dm
  code/modules/fabrication/designs/general/designs_general.dm
  code/modules/fabrication/designs/imprinter/designs_misc_circuits.dm
  code/modules/locks/key.dm
  code/modules/locks/lock_construct.dm
  code/modules/materials/_materials.dm
  code/modules/reagents/chems/chems_cleaner.dm
  code/modules/reagents/chems/chems_nutriment.dm
  code/modules/reagents/reactions/reaction_drugs.dm
  code/modules/reagents/reactions/reaction_other.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/vehicles/cargo_train.dm
  mods/persistence/modules/clothing/_clothing.dm
Labels: :new: enhancement, :microscope: Chemistry/Reagents/Materials

#485 Add emergency showers to outreach
  code/game/objects/structures/signs/direction_signs.dm
  code/game/objects/structures/watercloset.dm
  icons/obj/signs/slim_location_signs.dmi
  maps/outreach/outreach-1.dmm
  maps/outreach/outreach-2.dmm
  maps/outreach/outreach-3.dmm
  maps/outreach/outreach-4.dmm
Labels: :milky_way: map/map gen

#492 re-add client preferences to the character panel
  mods/persistence/modules/client/preference_setup/preference_setup.dm
Labels: :beetle: bug

#497 Early 2024 testing fixes
  code/datums/type_cloning.dm
  code/game/objects/items/devices/paint_sprayer.dm
  code/game/objects/structures/wall_frame.dm
  code/game/turfs/simulated/walls.dm
  code/modules/hydroponics/grown.dm
  code/modules/modular_computers/file_system/programs/generic/ntdownloader.dm
  code/modules/modular_computers/networking/machinery/telecomms.dm
  code/modules/modular_computers/networking/network_files.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/paperwork/printer.dm
  maps/outreach/outreach_zlevels.dm
  mods/persistence/modules/world_save/saved_vars/saved_misc.dm
Labels: :beetle: bug, :sweat_drops: port/upstream merge

#498 fix missing shower icon
  icons/obj/watercloset.dmi
Labels: :beetle: bug

#499 Adds a new 'cheap' infinite mining vendor
  mods/persistence/_persistence.dme
  mods/persistence/modules/chargen/items.dm
  mods/persistence/modules/chargen/storage/industrial_boxes.dm
  mods/persistence/modules/chargen/vending/industrial.dm
Labels: :new: enhancement, :heavy_dollar_sign: economy

#506 Network fixes and additions
  code/datums/extensions/network_lockable.dm
  code/game/machinery/_machines_base/machinery_components.dm
  code/game/machinery/_machines_base/stock_parts/network_lock.dm
  code/game/machinery/camera/camera.dm
  code/game/objects/structures/crates_lockers/closets/_closet_appearance_definitions.dm
  code/game/objects/structures/crates_lockers/closets/secure/network.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/fabrication/designs/industrial/designs_structure.dm
  code/modules/modular_computers/networking/accounts/_network_accounts.dm
  code/modules/modular_computers/networking/accounts/id_card.dm
  code/modules/modular_computers/networking/finance/money_accounts.dm
  mods/persistence/game/machinery/_machines_base/stock_parts/network_lock.dm
  nano/templates/network_lock.tmpl
  nebula.dme
Labels: :new: enhancement
